### ISSUE TITLE
Thinkpad t450/t450s MacOS Sequoia 15

### ISSUE THREAD

**Issue by matte-oss** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore#137]
Mac os sequoia stable Is now relased!👀

https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/issues/137#issuecomment-2766815876

And then patch the gpu with oclp: https://github.com/dortania/OpenCore-Legacy-Patcher/releases/

It should be working fine!

**Known issues:**
- ~~The integrated brightness slider doesn't work: Use [Brightness Slider](https://apps.apple.com/app/brightness-slider/id456624497?mt=12)~~
- ~~Volume Control using FN keys stopped working~~
- ~~Airportitlwm 2.3.0 doesn't work perfectly.~~

**Remember to change the serial using [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS)**

Let me know if there are any issues

[**MacOS Tahoe repo (beta)**](https://github.com/matte-oss/Thinkpad-T450-MacOS-Tahoe-Hackintosh)

**Comment by hlbomfim** [comment]
How U use OCLP? When install don`t ask to Allow in Privacy & Security.

**Comment by matte-oss** [comment]
> How U use OCLP? When install don`t ask to Allow in Privacy & Security.

Strange, for me It asks, After it's done patching before rebooting try seeing if you can allow It in the settings manually

**Comment by hlbomfim** [comment]
> > How U use OCLP? When install don`t ask to Allow in Privacy & Security.
> 
> Strange, for me It asks, After it's done patching before rebooting try seeing if you can allow It in the settings manually

![image](https://github.com/user-attachments/assets/2c298b51-9a41-4821-9804-e63bc49c59fd)

The problem. And the patch doesn't work

**Comment by Grabowskyy** [comment]
Same here with that issue. I can install macOS normally, but after patching, the system doesn't want to boot. I have a ThinkPad T450 with Intel I5 5300U processor, but for some reason in the system report it shows Intel I7
[log.txt](https://github.com/user-attachments/files/17777370/log.txt)
. Here's the log I got after macOS disabled the extention.

**Comment by matte-oss** [comment]
Sadly i haven't got time to look into this.

**Comment by lweixing55** [comment]
The integrated brightness slider does not work, the screen goes black when the device wakes up from sleep mode, and the OCLP patch does not work. I think These are all caused by the incomplete shielding of the independent graphics card.
Here is the solution：
1、acpi-path
     PCI0.VID to IGPU #2 (Thinkpad)       disable
     PCI0.VID to IGPU #1 (Thinkpad)        disable
2、dp-PciRoot(0x0)/Pci(0x2,0x0)       add
           disable-external-gpu(key)    01000000(value)        data(data-type)

Is anyone willing to try?

**Comment by Grabowskyy** [comment]
I actually decided to try your solution. I changed the config file according to your comment, created a separate partition for Sequoia and installed the system, but after patching the graphics with OCLP the system still kernel panicks. The report I got is exactly the same as the one I linked above. I should probably mention that when I went back to Sonoma I had to use older EFI because my MiniDP wasn't working.

**Comment by lweixing55** [comment]
> I actually decided to try your solution. I changed the config file according to your comment, created a separate partition for Sequoia and installed the system, but after patching the graphics with OCLP the system still kernel panicks. The report I got is exactly the same as the one I linked above. I should probably mention that when I went back to Sonoma I had to use older EFI because my MiniDP wasn't working.

Are your Lilu.kext and WhateverGreen.kext the latest versions? If not, please update to the latest version and try again.
I don't have an external monitor, so I didn't test MiniDP. Maybe you can try PCI0.VID to IGPU #1 (Thinkpad) enable.

I have T450 with i5-5200u  processor, and it works fine.
Good luck

**Comment by Grabowskyy** [comment]
Thank you for reminding me of the most important step which was updating kexts, becasue now it actually works. MiniDP still isn't working though. I'll try a few more things and if I get it to work I'm gonna update this comment. Thank you :)

**Comment by hlbomfim** [comment]
Sequoia 15.1 / Opencore 1.0.2 and OCLP 2.0.2+

EFI: https://drive.google.com/file/d/1KK0BCK-YCJCc1az_JF8zfR5GQtI9LOJh/view?usp=sharing

Problems: 

- Intel Network Adapter because Airportitlwn 2.3.0 doesn't work perfectly.
- Volume Control at FN keys stop to work
- Brightness: Install Brightness slider at AppStore

**Comment by Grabowskyy** [comment]
Ok so I fixed the MiniDP issue. I used my old EFI and updated all kexts in it. If there's anyone who would like to take a look and figure out why it works on this EFI then here's the link to download: https://drive.google.com/file/d/1sxtSm7SGBJ3kU9M_MsJN6AP_32n1uuVd/view?usp=sharing

Thank you :)

== EDIT ==

I replaced the link to download because I figured out why MiniDP wasn't working. It was all because of the System Product Name. In the EFI posted by @hlbomfim it is MacBookPro16,4 which uses UHD 630/Radeon Pro 5600M GPU, but the ThinkPad doesn't have that. I changed the System Product Name to MacBookPro16,3 and generated an entire SMBIOS for it and now MiniDP is working.

**Comment by hlbomfim** [comment]
> Ok so I fixed the MiniDP issue. I used my old EFI and updated all kexts in it. If there's anyone who would like to take a look and figure out why it works on this EFI then here's the link to download: https://drive.google.com/file/d/1sxtSm7SGBJ3kU9M_MsJN6AP_32n1uuVd/view?usp=sharing
> 
> Thank you :)
> 
> == EDIT ==
> 
> I replaced the link to download because I figured out why MiniDP wasn't working. It was all because of the System Product Name. In the EFI posted by @hlbomfim it is MacBookPro16,4 which uses UHD 630/Radeon Pro 5600M GPU, but the ThinkPad doesn't have that. I changed the System Product Name to MacBookPro16,3 and generated an entire SMBIOS for it and now MiniDP is working.

Let's try at night..

**Comment by hlbomfim** [comment]
> Ok so I fixed the MiniDP issue. I used my old EFI and updated all kexts in it. If there's anyone who would like to take a look and figure out why it works on this EFI then here's the link to download: https://drive.google.com/file/d/1sxtSm7SGBJ3kU9M_MsJN6AP_32n1uuVd/view?usp=sharing
> 
> Thank you :)
> 
> == EDIT ==
> 
> I replaced the link to download because I figured out why MiniDP wasn't working. It was all because of the System Product Name. In the EFI posted by @hlbomfim it is MacBookPro16,4 which uses UHD 630/Radeon Pro 5600M GPU, but the ThinkPad doesn't have that. I changed the System Product Name to MacBookPro16,3 and generated an entire SMBIOS for it and now MiniDP is working.

IT
WORKS...
GREAT...
WONDERFUL...

I change the serial :-)

2 Updates:

update BlueToolFixuo.kext and use this to enable bluetooth intel: https://elitemacx86.com/threads/how-to-fix-intel-wifi-and-bluetooth-on-macos-sequoia-and-later.2066/#-step-4-add-bluetooth-parameters

regards

**Comment by matte-oss** [comment]
I just formatted my MacOS partitinon while installing Arch Linux💀.

When i have time i'll reinstall MacOS and I will write a step to step guide.

**Comment by matte-oss** [comment]
I just formatted my MacOS partitinon while installing Arch Linux💀.

When i have time i'll reinstall MacOS and I will write a step to step guide.

**Comment by Dubpi** [comment]
i5 serie hd 4400 graphics intel.  what version is supported .Could I install Sonoma or Sequoia? I'm currently in Big Sur

**Comment by matte-oss** [comment]
Look at this:
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/issues/133#issuecomment-2766144014

**Comment by dj-nest** [comment]
I managed to make all the drivers to work on MacOS Sequoia V 15.3.1
with kexts and scripts on the latest open core V1.04

Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing

I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram
Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3
Geekbench scored 2076 on GPU and 2001 on CPU multicore.

Inside the .zip file you will find :
HeliPort.app (install in apps)
ThinkPadAssistant.app (install in apps)
ALCPlugFix (install the script with terminal)
And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)

https://www.youtube.com/watch?v=aKfBZlyYCfI

What doesn’t work:

Nothing everything works fine, Im testing it for a week and didnt have any issues at all.

What works ?

Wi-Fi with heliport.app and itlwm.kext.
Bluetooth works fine with the added kexts and scripts on the NVRAM section.
Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added
codecCommander kext to make the audio output fix to work without the sleep bug fix.
Sleep and Wake works Just fine without any issues.
All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext
Volume FN keys working fine including mute , sound minus , sound plus , mic mute
With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch
Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad.
MiniDisplayport works just fine.

Added Blackosx\BsxlmacSilver menu on Picker.

Test it and see if it works fine.

**Comment by PeiFengBin** [comment]
> I managed to make all the drivers to work on MacOS Sequoia V 15.3.1 with kexts and scripts on the latest open core V1.04
> 
> Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing
> 
> I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3 Geekbench scored 2076 on GPU and 2001 on CPU multicore.
> 
> Inside the .zip file you will find : HeliPort.app (install in apps) ThinkPadAssistant.app (install in apps) ALCPlugFix (install the script with terminal) And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)
> 
> https://www.youtube.com/watch?v=aKfBZlyYCfI
> 
> What doesn’t work:
> 
> Nothing everything works fine, Im testing it for a week and didnt have any issues at all.
> 
> What works ?
> 
> Wi-Fi with heliport.app and itlwm.kext. Bluetooth works fine with the added kexts and scripts on the NVRAM section. Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added codecCommander kext to make the audio output fix to work without the sleep bug fix. Sleep and Wake works Just fine without any issues. All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext Volume FN keys working fine including mute , sound minus , sound plus , mic mute With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad. MiniDisplayport works just fine.
> 
> Added Blackosx\BsxlmacSilver menu on Picker.
> 
> Test it and see if it works fine.

First of all, thank you very much for your EFI, now my T450S is successfully running Sequoia V 15.3.1.
But now there is a problem, that is, after logging in, the desktop has no background, it is pure white, and the Display is unknown, I don't know how to debug it, can you point me to it?

**Comment by hlbomfim** [comment]
> > I managed to make all the drivers to work on MacOS Sequoia V 15.3.1 with kexts and scripts on the latest open core V1.04
> > Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing
> > I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3 Geekbench scored 2076 on GPU and 2001 on CPU multicore.
> > Inside the .zip file you will find : HeliPort.app (install in apps) ThinkPadAssistant.app (install in apps) ALCPlugFix (install the script with terminal) And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)
> > https://www.youtube.com/watch?v=aKfBZlyYCfI
> > What doesn’t work:
> > Nothing everything works fine, Im testing it for a week and didnt have any issues at all.
> > What works ?
> > Wi-Fi with heliport.app and itlwm.kext. Bluetooth works fine with the added kexts and scripts on the NVRAM section. Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added codecCommander kext to make the audio output fix to work without the sleep bug fix. Sleep and Wake works Just fine without any issues. All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext Volume FN keys working fine including mute , sound minus , sound plus , mic mute With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad. MiniDisplayport works just fine.
> > Added Blackosx\BsxlmacSilver menu on Picker.
> > Test it and see if it works fine.
> 
> First of all, thank you very much for your EFI, now my T450S is successfully running Sequoia V 15.3.1. But now there is a problem, that is, after logging in, the desktop has no background, it is pure white, and the Display is unknown, I don't know how to debug it, can you point me to it?

Hello. Just install and run OCLP:  https://github.com/dortania/OpenCore-Legacy-Patcher/

At.te,

**Comment by PeiFengBin** [comment]
> > > I managed to make all the drivers to work on MacOS Sequoia V 15.3.1 with kexts and scripts on the latest open core V1.04
> > > Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing
> > > I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3 Geekbench scored 2076 on GPU and 2001 on CPU multicore.
> > > Inside the .zip file you will find : HeliPort.app (install in apps) ThinkPadAssistant.app (install in apps) ALCPlugFix (install the script with terminal) And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)
> > > https://www.youtube.com/watch?v=aKfBZlyYCfI
> > > What doesn’t work:
> > > Nothing everything works fine, Im testing it for a week and didnt have any issues at all.
> > > What works ?
> > > Wi-Fi with heliport.app and itlwm.kext. Bluetooth works fine with the added kexts and scripts on the NVRAM section. Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added codecCommander kext to make the audio output fix to work without the sleep bug fix. Sleep and Wake works Just fine without any issues. All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext Volume FN keys working fine including mute , sound minus , sound plus , mic mute With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad. MiniDisplayport works just fine.
> > > Added Blackosx\BsxlmacSilver menu on Picker.
> > > Test it and see if it works fine.
> > 
> > First of all, thank you very much for your EFI, now my T450S is successfully running Sequoia V 15.3.1. But now there is a problem, that is, after logging in, the desktop has no background, it is pure white, and the Display is unknown, I don't know how to debug it, can you point me to it?
> 
> Hello. Just install and run OCLP:  https://github.com/dortania/OpenCore-Legacy-Patcher/
> 
> At.te,

Your guidance is very useful. The problem has been solved. Thank you very much.👍👍👍

**Comment by matte-oss** [comment]
I managed to get the Tahoe beta to boot, but no  OCLP support of course

https://github.com/matte-oss/Thinkpad-T450-MacOS-Tahoe-Hackintosh

**Comment by hlbomfim** [comment]
> I managed to get the Tahoe beta to boot, but no OCLP support of course
> 
> https://github.com/matte-oss/Thinkpad-T450-MacOS-Tahoe-Hackintosh

great....

**Comment by Linwayne04** [comment]
> I managed to make all the drivers to work on MacOS Sequoia V 15.3.1 with kexts and scripts on the latest open core V1.04
> 
> Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing
> 
> I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3 Geekbench scored 2076 on GPU and 2001 on CPU multicore.
> 
> Inside the .zip file you will find : HeliPort.app (install in apps) ThinkPadAssistant.app (install in apps) ALCPlugFix (install the script with terminal) And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)
> 
> https://www.youtube.com/watch?v=aKfBZlyYCfI
> 
> What doesn’t work:
> 
> Nothing everything works fine, Im testing it for a week and didnt have any issues at all.
> 
> What works ?
> 
> Wi-Fi with heliport.app and itlwm.kext. Bluetooth works fine with the added kexts and scripts on the NVRAM section. Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added codecCommander kext to make the audio output fix to work without the sleep bug fix. Sleep and Wake works Just fine without any issues. All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext Volume FN keys working fine including mute , sound minus , sound plus , mic mute With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad. MiniDisplayport works just fine.
> 
> Added Blackosx\BsxlmacSilver menu on Picker.
> 
> Test it and see if it works fine.

If anyone wants to use native wifi, here is the workaround: https://www.reddit.com/r/hackintosh/comments/1lljg1l/how_to_get_airportitlwm_working_on_sequoia

**Comment by DatenRaten** [comment]
> I managed to make all the drivers to work on MacOS Sequoia V 15.3.1 with kexts and scripts on the latest open core V1.04
> 
> Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing
> 
> I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3 Geekbench scored 2076 on GPU and 2001 on CPU multicore.
> 
> Inside the .zip file you will find : HeliPort.app (install in apps) ThinkPadAssistant.app (install in apps) ALCPlugFix (install the script with terminal) And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)
> 
> https://www.youtube.com/watch?v=aKfBZlyYCfI
> 
> What doesn’t work:
> 
> Nothing everything works fine, Im testing it for a week and didnt have any issues at all.
> 
> What works ?
> 
> Wi-Fi with heliport.app and itlwm.kext. Bluetooth works fine with the added kexts and scripts on the NVRAM section. Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added codecCommander kext to make the audio output fix to work without the sleep bug fix. Sleep and Wake works Just fine without any issues. All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext Volume FN keys working fine including mute , sound minus , sound plus , mic mute With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad. MiniDisplayport works just fine.
> 
> Added Blackosx\BsxlmacSilver menu on Picker.
> 
> Test it and see if it works fine.

Quick service post:
your EFI works great for me! I did however notice that PerfPowerServices takes about 70% CPU and kernel_task about 40% CPU.
After updating VirtualSMC.kext to its latest version this issue is fixed and my system now runs noticeably better.

Just in case other face this issue. Thank you for providing this EFI!

**Comment by dandycheung** [comment]
> I managed to make all the drivers to work on MacOS Sequoia V 15.3.1 with kexts and scripts on the latest open core V1.04
> 
> Download Link: https://drive.google.com/file/d/1Wi4aq5cRqrWG0htYbBOUXW5_Mi7UpBTj/view?usp=sharing
> 
> I got a T450s with i7-5600U , Intel HD5500 with VRAM 2GB and 20GB DDR3 Ram Video Card is spoofed with Intel Iris 6100 and stats for MacBookPro 16,3 Geekbench scored 2076 on GPU and 2001 on CPU multicore.
> 
> Inside the .zip file you will find : HeliPort.app (install in apps) ThinkPadAssistant.app (install in apps) ALCPlugFix (install the script with terminal) And GenSMBIOS scripts to change the SerialNumber (install the script with terminal, READ the readme)
> 
> https://www.youtube.com/watch?v=aKfBZlyYCfI
> 
> What doesn’t work:
> 
> Nothing everything works fine, Im testing it for a week and didnt have any issues at all.
> 
> What works ?
> 
> Wi-Fi with heliport.app and itlwm.kext. Bluetooth works fine with the added kexts and scripts on the NVRAM section. Audio Headphones Output works fine with the ALCplugfix script from ClayBIOS, and also I added codecCommander kext to make the audio output fix to work without the sleep bug fix. Sleep and Wake works Just fine without any issues. All the FN keys are now working fine including the brightness keys using the AppleBacklightfixup.kext Volume FN keys working fine including mute , sound minus , sound plus , mic mute With the Thinkpad Assistant app CapsLock works , FN + space shows the backlight function and F7 switch Between Laptop Screen and Mini DisplayPort. F9 bring the settings screen F12 brings the Launchpad. MiniDisplayport works just fine.
> 
> Added Blackosx\BsxlmacSilver menu on Picker.
> 
> Test it and see if it works fine.

I upgraded my T450s (i7-5600U, Intel & NVidia dual GPU, 20GB memory) from Monterey to Sequoia 15.7 last night. Everything is perfect until I input my password to login. The loading icon will never end, so I cannot enter my desktop anymore. Not solved now, any ‌suggestions? Thank you.

**Comment by MizhiDR** [comment]
I have installed macOS Sequoia and patched the HD5500 using OCLP, but I am currently experiencing problems shutting down and restarting. How can I resolve this?

**Comment by sofianism** [comment]
Hi everyone !! My first contribution on GitHub :) 
Here's my EFI that includes kext for Touchscreen ability + original Broadcom wireless support 
https://drive.google.com/file/d/1U-PXS8EpeSDMWldlYIAU5YRk0qC6ojWP/view?usp=sharing
Hope it will help :)
